/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2024-11-13T15:06:25.288+05:30
  3.47.0.99999
  
  Standalone prediction code with sample test data for GBMModel named gbm_360f02d7_7617_4a24_9db0_82271c52eb86

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://172.16.0.18:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://172.16.0.18:54321/3/Models.java/gbm-360f02d7-7617-4a24-9db0-82271c52eb86 > gbm_360f02d7_7617_4a24_9db0_82271c52eb86.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm_360f02d7_7617_4a24_9db0_82271c52eb86.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package com.intense.mlapi.models;
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm_360f02d7_7617_4a24_9db0_82271c52eb86", algorithm="gbm")
public class gbm_360f02d7_7617_4a24_9db0_82271c52eb86 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 8; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm_360f02d7_7617_4a24_9db0_82271c52eb86.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* baseFare */ null,
    /* reservationCharge */ null,
    /* superfastCharge */ null,
    /* serviceTax */ null,
    /* cateringCharge */ null,
    /* dynamicFare */ null,
    /* distance */ null,
    /* duration */ null,
    /* totalFare */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm_360f02d7_7617_4a24_9db0_82271c52eb86() { super(NAMES,DOMAINS,"totalFare"); }
  public String getUUID() { return Long.toString(-9209159902336536288L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_0.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_1.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_2.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_3.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_4.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_5.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_6.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_7.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_8.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_9.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_10.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_11.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_12.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_13.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_14.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_15.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_16.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_17.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_18.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_19.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_20.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_21.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_22.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_23.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_24.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_25.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_26.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_27.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_28.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_29.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_30.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_31.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_32.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_33.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_34.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_35.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_36.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_37.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_38.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_39.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_40.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_41.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_42.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_43.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_44.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_45.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_46.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_47.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_48.score0(data,preds);
    gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_49.score0(data,preds);
    preds[0] += 1000.4512355404622;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm_360f02d7_7617_4a24_9db0_82271c52eb86 implements java.io.Serializable {
  public static final String[] VALUES = new String[8];
  static {
    NamesHolder_gbm_360f02d7_7617_4a24_9db0_82271c52eb86_0.fill(VALUES);
  }
  static final class NamesHolder_gbm_360f02d7_7617_4a24_9db0_82271c52eb86_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "baseFare";
      sa[1] = "reservationCharge";
      sa[2] = "superfastCharge";
      sa[3] = "serviceTax";
      sa[4] = "cateringCharge";
      sa[5] = "dynamicFare";
      sa[6] = "distance";
      sa[7] = "duration";
    }
  }
}

class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_0_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 70.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 602.5f ? 
             (Double.isNaN(data[0]) || data[0 /* baseFare */] < 313.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 172.0f ? 
                     (data[0 /* baseFare */] < 97.5f ? 
                        -91.7654f : 
                        -84.12271f) : 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 231.5f ? 
                        -75.13536f : 
                        -68.532104f)) : 
                 (data[0 /* baseFare */] < 435.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 58.0f ? 
                        -59.11514f : 
                        -29.606527f) : 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 501.5f ? 
                        -47.824368f : 
                        -38.53137f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 48.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 714.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 34.5f ? 
                        -29.445747f : 
                        -23.35155f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 44.5f ? 
                        -13.051216f : 
                        -3.065526f)) : 
                 (data[3 /* serviceTax */] < 58.5f ? 
                     (data[3 /* serviceTax */] < 53.5f ? 
                        6.5429835f : 
                        17.155481f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 64.5f ? 
                        27.203423f : 
                        41.718506f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 132.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 96.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 82.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 76.5f ? 
                        53.521645f : 
                        66.65293f) : 
                     (data[3 /* serviceTax */] < 88.5f ? 
                        79.36776f : 
                        93.889656f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 113.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 104.5f ? 
                        111.394844f : 
                        129.3048f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 122.5f ? 
                        147.68129f : 
                        167.24248f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 181.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 155.5f ? 
                     (data[3 /* serviceTax */] < 141.5f ? 
                        188.47456f : 
                        213.2231f) : 
                     (data[3 /* serviceTax */] < 165.5f ? 
                        239.34747f : 
                        266.92056f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 226.5f ? 
                     (data[3 /* serviceTax */] < 197.5f ? 
                        302.07297f : 
                        346.7867f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 259.5f ? 
                        411.15552f : 
                        484.30887f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_1_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 71.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 691.5f ? 
             (data[0 /* baseFare */] < 371.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 202.5f ? 
                     (data[0 /* baseFare */] < 107.0f ? 
                        -82.43688f : 
                        -74.961685f) : 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 276.5f ? 
                        -65.1568f : 
                        -56.690296f)) : 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 562.0f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 24.5f ? 
                        -45.039043f : 
                        -37.479378f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 35.5f ? 
                        -27.518654f : 
                        -21.176016f))) : 
             (data[3 /* serviceTax */] < 54.0f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 45.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 165.0f ? 
                        -12.646106f : 
                        26.080824f) : 
                     (data[3 /* serviceTax */] < 49.5f ? 
                        -0.6493859f : 
                        6.7310405f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 62.5f ? 
                     (data[3 /* serviceTax */] < 57.5f ? 
                        14.88679f : 
                        22.837122f) : 
                     (data[3 /* serviceTax */] < 67.5f ? 
                        32.366596f : 
                        41.255768f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 134.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 98.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 83.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 77.5f ? 
                        50.290154f : 
                        61.700478f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 90.5f ? 
                        74.16969f : 
                        88.519264f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 115.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 107.5f ? 
                        104.352425f : 
                        121.31733f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 126.5f ? 
                        139.55421f : 
                        157.95705f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 183.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 156.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 147.5f ? 
                        177.34932f : 
                        199.59659f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 169.5f ? 
                        219.68811f : 
                        246.85045f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 228.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 204.5f ? 
                        280.09943f : 
                        320.77576f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 266.5f ? 
                        377.1881f : 
                        448.79697f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_2_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 72.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 704.5f ? 
             (data[0 /* baseFare */] < 370.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 205.5f ? 
                     (data[0 /* baseFare */] < 112.5f ? 
                        -74.14635f : 
                        -67.23857f) : 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 275.5f ? 
                        -58.236057f : 
                        -51.020683f)) : 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 571.5f ? 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 490.5f ? 
                        -40.039623f : 
                        -32.474792f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 11.5f ? 
                        -22.758717f : 
                        9.447359f))) : 
             (data[3 /* serviceTax */] < 54.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 46.5f ? 
                     (data[0 /* baseFare */] < 783.5f ? 
                        -13.336656f : 
                        -5.947654f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 50.5f ? 
                        1.716537f : 
                        8.07145f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 63.5f ? 
                     (data[3 /* serviceTax */] < 58.5f ? 
                        14.559438f : 
                        21.432228f) : 
                     (data[3 /* serviceTax */] < 67.5f ? 
                        29.900549f : 
                        37.635033f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 134.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 99.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 86.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 79.5f ? 
                        47.694008f : 
                        59.624252f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 93.5f ? 
                        71.90538f : 
                        83.22762f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 115.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 108.5f ? 
                        95.92942f : 
                        110.47324f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 124.5f ? 
                        124.08681f : 
                        140.29729f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 185.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 157.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 146.5f ? 
                        158.9233f : 
                        179.52832f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 169.5f ? 
                        198.92888f : 
                        223.60371f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 236.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 208.5f ? 
                        257.41226f : 
                        297.82404f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 306.5f ? 
                        355.13663f : 
                        451.1385f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_3_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 69.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 602.5f ? 
             (Double.isNaN(data[0]) || data[0 /* baseFare */] < 320.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 167.5f ? 
                     (data[0 /* baseFare */] < 87.5f ? 
                        -67.1501f : 
                        -61.62743f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 26.5f ? 
                        -52.89935f : 
                        -30.011913f)) : 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 442.5f ? 
                     (data[3 /* serviceTax */] < 21.5f ? 
                        -43.013885f : 
                        -36.016052f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 28.5f ? 
                        -32.36142f : 
                        -24.181934f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 48.0f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 735.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 36.0f ? 
                        -21.37214f : 
                        -16.235361f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 233.0f ? 
                        -7.052627f : 
                        32.757736f)) : 
                 (data[3 /* serviceTax */] < 57.5f ? 
                     (data[3 /* serviceTax */] < 52.5f ? 
                        3.3038814f : 
                        11.471324f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 63.5f ? 
                        18.989573f : 
                        29.024443f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 130.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 95.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 81.5f ? 
                     (data[3 /* serviceTax */] < 74.5f ? 
                        36.46618f : 
                        46.326893f) : 
                     (data[3 /* serviceTax */] < 87.5f ? 
                        56.463055f : 
                        67.21184f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 110.0f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 195.0f ? 
                        82.9453f : 
                        116.49168f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 119.5f ? 
                        102.8813f : 
                        118.99028f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 182.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 150.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        139.90227f : 
                        174.7374f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 165.5f ? 
                        170.78276f : 
                        195.76263f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 223.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 402.5f ? 
                        231.24731f : 
                        282.8352f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 251.5f ? 
                        292.11813f : 
                        348.54865f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_4_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 70.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 615.5f ? 
             (Double.isNaN(data[0]) || data[0 /* baseFare */] < 320.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 188.0f ? 
                     (data[0 /* baseFare */] < 93.0f ? 
                        -60.32754f : 
                        -55.063316f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 50.5f ? 
                        -46.93944f : 
                        -24.597427f)) : 
                 (data[0 /* baseFare */] < 436.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 58.0f ? 
                        -38.78935f : 
                        -13.78324f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 28.5f ? 
                        -30.55516f : 
                        -21.549522f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 48.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 748.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 87.5f ? 
                        -17.296314f : 
                        13.6752205f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 233.0f ? 
                        -5.333269f : 
                        34.1871f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 61.5f ? 
                     (data[3 /* serviceTax */] < 55.5f ? 
                        5.3259487f : 
                        14.514641f) : 
                     (data[3 /* serviceTax */] < 66.5f ? 
                        22.455612f : 
                        28.973118f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 132.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 97.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 83.5f ? 
                     (data[3 /* serviceTax */] < 75.5f ? 
                        34.10862f : 
                        43.589603f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 90.5f ? 
                        54.077187f : 
                        63.57287f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 113.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 105.5f ? 
                        73.79338f : 
                        85.92216f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 195.0f ? 
                        101.39139f : 
                        137.06578f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 191.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 161.5f ? 
                     (data[3 /* serviceTax */] < 144.5f ? 
                        125.15012f : 
                        146.14606f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 280.0f ? 
                        173.10088f : 
                        214.02325f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 240.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 216.5f ? 
                        217.75522f : 
                        249.8157f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 283.5f ? 
                        291.6004f : 
                        371.17398f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_5_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 72.5f ? 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 37.5f ? 
             (data[0 /* baseFare */] < 388.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 206.5f ? 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 136.5f ? 
                        -51.473236f : 
                        -46.620277f) : 
                     (data[0 /* baseFare */] < 266.5f ? 
                        -42.793392f : 
                        -36.96008f)) : 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 545.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 24.5f ? 
                        -29.678286f : 
                        -24.58165f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 155.0f ? 
                        -16.810717f : 
                        27.286789f))) : 
             (data[3 /* serviceTax */] < 54.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 46.5f ? 
                     (data[3 /* serviceTax */] < 42.5f ? 
                        -8.863036f : 
                        -3.4731004f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 133.0f ? 
                        3.1035862f : 
                        29.682648f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 62.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 59.5f ? 
                        10.78577f : 
                        15.646021f) : 
                     (data[3 /* serviceTax */] < 67.5f ? 
                        21.218782f : 
                        27.463694f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 138.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 100.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 85.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 78.5f ? 
                        34.165684f : 
                        42.434887f) : 
                     (data[3 /* serviceTax */] < 92.5f ? 
                        51.136894f : 
                        60.49349f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 118.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        75.05671f : 
                        105.018234f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        98.02016f : 
                        129.47807f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 193.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 163.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 280.0f ? 
                        126.429535f : 
                        166.53398f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 280.0f ? 
                        158.32985f : 
                        196.23193f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 245.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 217.5f ? 
                        198.5153f : 
                        228.97397f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 852.5f ? 
                        273.5662f : 
                        400.86127f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_6_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 71.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 665.5f ? 
             (data[0 /* baseFare */] < 350.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 190.5f ? 
                     (data[0 /* baseFare */] < 81.5f ? 
                        -49.33129f : 
                        -44.509186f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 50.0f ? 
                        -37.467316f : 
                        -16.231234f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 28.5f ? 
                     (data[0 /* baseFare */] < 434.5f ? 
                        -30.50274f : 
                        -24.481724f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 34.5f ? 
                        -16.333572f : 
                        -12.164188f))) : 
             (data[3 /* serviceTax */] < 52.0f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 817.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 97.5f ? 
                        -8.976991f : 
                        15.215004f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 208.5f ? 
                        -0.035555143f : 
                        32.901955f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 60.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 56.5f ? 
                        7.8544316f : 
                        12.797386f) : 
                     (data[3 /* serviceTax */] < 66.5f ? 
                        17.7973f : 
                        23.949005f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 128.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 94.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 81.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 73.5f ? 
                        31.281363f : 
                        56.09105f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 156.0f ? 
                        44.001915f : 
                        72.81879f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 109.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 161.0f ? 
                        59.63987f : 
                        86.98412f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 229.0f ? 
                        77.83208f : 
                        106.23458f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 176.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 148.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 195.0f ? 
                        99.738174f : 
                        129.30203f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 229.0f ? 
                        125.38412f : 
                        157.2838f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 215.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 402.5f ? 
                        162.55307f : 
                        208.77078f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 245.5f ? 
                        205.16599f : 
                        250.63597f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_7_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 73.5f ? 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 38.5f ? 
             (data[0 /* baseFare */] < 387.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 211.5f ? 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 142.0f ? 
                        -41.730747f : 
                        -37.55416f) : 
                     (data[0 /* baseFare */] < 266.5f ? 
                        -34.663193f : 
                        -29.79519f)) : 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 585.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 87.5f ? 
                        -22.579575f : 
                        2.4441845f) : 
                     (Double.isNaN(data[5]) || data[5 /* dynamicFare */] < 92.0f ? 
                        -12.921617f : 
                        37.94289f))) : 
             (data[3 /* serviceTax */] < 55.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 47.5f ? 
                     (data[3 /* serviceTax */] < 42.5f ? 
                        -6.625151f : 
                        -2.3901882f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 133.0f ? 
                        3.262182f : 
                        24.817434f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 65.5f ? 
                     (data[3 /* serviceTax */] < 59.5f ? 
                        8.99822f : 
                        13.6635f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 79.5f ? 
                        21.31274f : 
                        42.105705f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 139.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 102.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 86.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 165.0f ? 
                        31.627989f : 
                        56.94493f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 133.0f ? 
                        45.846935f : 
                        71.806755f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 120.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 229.0f ? 
                        62.65824f : 
                        90.05175f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 195.0f ? 
                        81.46955f : 
                        107.17079f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 194.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 161.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 147.0f ? 
                        101.685524f : 
                        127.12998f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 280.0f ? 
                        127.33544f : 
                        157.73477f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 239.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 488.5f ? 
                        165.07057f : 
                        215.62755f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 306.5f ? 
                        211.79277f : 
                        287.70972f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_8_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 69.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 615.5f ? 
             (data[0 /* baseFare */] < 295.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 151.5f ? 
                     (data[0 /* baseFare */] < 67.5f ? 
                        -41.774185f : 
                        -36.80479f) : 
                     (Double.isNaN(data[2]) || data[2 /* superfastCharge */] < 38.0f ? 
                        -32.52894f : 
                        -24.993938f)) : 
                 (data[0 /* baseFare */] < 431.0f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 89.0f ? 
                        -26.040298f : 
                        -3.8370836f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 58.0f ? 
                        -19.493343f : 
                        6.3283415f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 50.0f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 764.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 35.0f ? 
                        -12.703234f : 
                        -8.818116f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 233.0f ? 
                        -2.4328446f : 
                        24.806988f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 60.5f ? 
                     (data[3 /* serviceTax */] < 55.5f ? 
                        4.158758f : 
                        9.246345f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 108.0f ? 
                        15.640067f : 
                        35.928738f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 128.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 94.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 80.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 133.0f ? 
                        23.734486f : 
                        46.6471f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 78.0f ? 
                        35.143806f : 
                        56.740417f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 110.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 81.0f ? 
                        48.537502f : 
                        70.07591f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 81.0f ? 
                        63.563652f : 
                        85.28149f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 178.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 150.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 81.0f ? 
                        81.39102f : 
                        104.204124f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        103.22781f : 
                        128.63428f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 217.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 402.5f ? 
                        133.20135f : 
                        170.10777f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 270.5f ? 
                        174.04877f : 
                        229.74623f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_9_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 73.5f ? 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 38.5f ? 
             (data[0 /* baseFare */] < 398.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 205.5f ? 
                     (Double.isNaN(data[2]) || data[2 /* superfastCharge */] < 23.0f ? 
                        -33.787285f : 
                        -29.861769f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 50.0f ? 
                        -26.13049f : 
                        -7.9576783f)) : 
                 (data[0 /* baseFare */] < 533.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 25.5f ? 
                        -19.911854f : 
                        -15.877033f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 194.5f ? 
                        -10.991056f : 
                        23.513227f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 56.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 49.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 44.5f ? 
                        -4.497665f : 
                        -0.3911471f) : 
                     (data[3 /* serviceTax */] < 52.5f ? 
                        2.3710668f : 
                        5.954599f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 65.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 115.0f ? 
                        10.312761f : 
                        31.440252f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 155.0f ? 
                        17.268898f : 
                        37.828697f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 136.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 101.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 87.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 165.0f ? 
                        25.96397f : 
                        47.53906f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 133.0f ? 
                        37.35875f : 
                        58.15964f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 117.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        49.178417f : 
                        68.88947f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 349.5f ? 
                        63.742577f : 
                        93.81338f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 194.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 159.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 294.0f ? 
                        80.785675f : 
                        109.26608f) : 
                     (data[3 /* serviceTax */] < 172.5f ? 
                        96.37245f : 
                        111.686195f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 239.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 488.5f ? 
                        133.80676f : 
                        176.93088f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 661.0f ? 
                        171.85637f : 
                        240.51189f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_10_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 74.5f ? 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 37.5f ? 
             (data[0 /* baseFare */] < 355.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 158.5f ? 
                     (data[0 /* baseFare */] < 60.5f ? 
                        -34.38979f : 
                        -29.799637f) : 
                     (Double.isNaN(data[2]) || data[2 /* superfastCharge */] < 8.0f ? 
                        -26.439718f : 
                        -22.358128f)) : 
                 (data[0 /* baseFare */] < 515.5f ? 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 24.5f ? 
                        -18.489265f : 
                        -14.443333f) : 
                     (Double.isNaN(data[5]) || data[5 /* dynamicFare */] < 108.5f ? 
                        -10.137231f : 
                        29.07088f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 56.5f ? 
                 (data[3 /* serviceTax */] < 48.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 86.5f ? 
                        -3.1611545f : 
                        11.354126f) : 
                     (data[3 /* serviceTax */] < 51.5f ? 
                        1.3728797f : 
                        5.198084f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 65.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 115.0f ? 
                        9.2814865f : 
                        28.296223f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 176.5f ? 
                        15.722217f : 
                        34.966732f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 140.5f ? 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 103.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 89.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 224.5f ? 
                        24.258749f : 
                        46.184856f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 224.5f ? 
                        35.05193f : 
                        56.80757f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 121.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 282.5f ? 
                        46.6993f : 
                        71.37465f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 282.5f ? 
                        60.49166f : 
                        86.82466f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 197.5f ? 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 170.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 294.0f ? 
                        77.2919f : 
                        101.934875f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 266.0f ? 
                        97.59238f : 
                        123.38434f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 244.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 488.5f ? 
                        123.61507f : 
                        162.55351f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 281.0f ? 
                        156.7588f : 
                        209.75237f)))));
    return pred;
  } // constant pool size = 126B, number of visited nodes = 31, static init size = 0B
}


class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_11_class_0.score0(fdata);
  }
}
class gbm_360f02d7_7617_4a24_9db0_82271c52eb86_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 75.5f ? 
         (Double.isNaN(data[0]) || data[0 /* baseFare */] < 716.5f ? 
             (data[0 /* baseFare */] < 341.5f ? 
                 (Double.isNaN(data[0]) || data[0 /* baseFare */] < 163.0f ? 
                     (Double.isNaN(data[2]) || data[2 /* superfastCharge */] < 23.0f ? 
                        -27.88429f : 
                        -24.584652f) : 
                     (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 15.5f ? 
                        -22.970047f : 
                        -14.723365f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 30.5f ? 
                     (Double.isNaN(data[0]) || data[0 /* baseFare */] < 442.5f ? 
                        -16.856728f : 
                        -13.227845f) : 
                     (Double.isNaN(data[5]) || data[5 /* dynamicFare */] < 53.5f ? 
                        -8.253864f : 
                        8.816303f))) : 
             (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 58.0f ? 
                 (data[0 /* baseFare */] < 856.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 97.5f ? 
                        -3.58814f : 
                        14.851547f) : 
                     (data[0 /* baseFare */] < 970.5f ? 
                        1.2872999f : 
                        4.9505544f)) : 
                 (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 66.5f ? 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 154.5f ? 
                        8.796986f : 
                        28.767614f) : 
                     (Double.isNaN(data[4]) || data[4 /* cateringCharge */] < 79.5f ? 
                        14.595929f : 
                        28.446815f)))) : 
         (Double.isNaN(data[3]) || data[3 /* serviceTax */] < 139.5f ? 