/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2024-12-30T14:43:56.363+05:30
  3.47.0.99999
  
  Standalone prediction code with sample test data for GBMModel named gbm_a1d31c0a_288b_44e5_933a_a802108402d6

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://172.16.0.18:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://172.16.0.18:54321/3/Models.java/gbm-a1d31c0a-288b-44e5-933a-a802108402d6 > gbm_a1d31c0a_288b_44e5_933a_a802108402d6.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m gbm_a1d31c0a_288b_44e5_933a_a802108402d6.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
package com.intense.mlapi.models;
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="gbm_a1d31c0a_288b_44e5_933a_a802108402d6", algorithm="gbm")
public class gbm_a1d31c0a_288b_44e5_933a_a802108402d6 extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Regression; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 8; }
  public int nclasses() { return 1; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_gbm_a1d31c0a_288b_44e5_933a_a802108402d6.VALUES;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* Project Type */ gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_0.VALUES,
    /* Region */ gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_1.VALUES,
    /* Department */ gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_2.VALUES,
    /* Complexity */ gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_3.VALUES,
    /* Completion% */ null,
    /* Phase */ gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_5.VALUES,
    /* Start Date */ null,
    /* End Date */ null,
    /* Project Cost */ null
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {1.0};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {1.0};

  public gbm_a1d31c0a_288b_44e5_933a_a802108402d6() { super(NAMES,DOMAINS,"Project Cost"); }
  public String getUUID() { return Long.toString(-8405708285285603288L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_0.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_1.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_2.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_3.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_4.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_5.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_6.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_7.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_8.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_9.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_10.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_11.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_12.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_13.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_14.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_15.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_16.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_17.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_18.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_19.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_20.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_21.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_22.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_23.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_24.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_25.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_26.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_27.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_28.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_29.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_30.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_31.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_32.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_33.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_34.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_35.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_36.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_37.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_38.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_39.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_40.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_41.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_42.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_43.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_44.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_45.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_46.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_47.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_48.score0(data,preds);
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_49.score0(data,preds);
    preds[0] += 4136458.506666667;
    preds[0] = preds[0];
    return preds;
  }
}
// The class representing training column names
class NamesHolder_gbm_a1d31c0a_288b_44e5_933a_a802108402d6 implements java.io.Serializable {
  public static final String[] VALUES = new String[8];
  static {
    NamesHolder_gbm_a1d31c0a_288b_44e5_933a_a802108402d6_0.fill(VALUES);
  }
  static final class NamesHolder_gbm_a1d31c0a_288b_44e5_933a_a802108402d6_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Project Type";
      sa[1] = "Region";
      sa[2] = "Department";
      sa[3] = "Complexity";
      sa[4] = "Completion%";
      sa[5] = "Phase";
      sa[6] = "Start Date";
      sa[7] = "End Date";
    }
  }
}
// The class representing column Project Type
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_0 implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_0_0.fill(VALUES);
  }
  static final class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_0_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "COST REDUCTION";
      sa[1] = "INCOME GENERATION";
      sa[2] = "PROCESS IMPROVEMENT";
      sa[3] = "WORKING CAPITAL IMPROVEMENT";
    }
  }
}
// The class representing column Region
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_1 implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_1_0.fill(VALUES);
  }
  static final class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_1_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "East";
      sa[1] = "North";
      sa[2] = "South";
      sa[3] = "West";
    }
  }
}
// The class representing column Department
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_2 implements java.io.Serializable {
  public static final String[] VALUES = new String[5];
  static {
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_2_0.fill(VALUES);
  }
  static final class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_2_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Admin & BI";
      sa[1] = "Sales and Marketing";
      sa[2] = "Supply Chain";
      sa[3] = "Warehouse";
      sa[4] = "eCommerce";
    }
  }
}
// The class representing column Complexity
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_3 implements java.io.Serializable {
  public static final String[] VALUES = new String[3];
  static {
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_3_0.fill(VALUES);
  }
  static final class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_3_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "High";
      sa[1] = "Low";
      sa[2] = "Medium";
    }
  }
}
// The class representing column Phase
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_5 implements java.io.Serializable {
  public static final String[] VALUES = new String[5];
  static {
    gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_5_0.fill(VALUES);
  }
  static final class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_ColInfo_5_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "Phase 1 - Explore";
      sa[1] = "Phase 2 - Develop";
      sa[2] = "Phase 3 - Plan";
      sa[3] = "Phase 4 - Implement";
      sa[4] = "Phase 5 - Measure";
    }
  }
}

class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_0_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (data[4 /* Completion% */] < 0.75992185f ? 
            30867.61f : 
             (data[7 /* End Date */] < 1.66464179E12f ? 
                -66634.766f : 
                 (data[4 /* Completion% */] < 0.85535157f ? 
                    11647.47f : 
                    -33482.523f))) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
            -2611.3955f : 
            61061.098f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_1_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (data[4 /* Completion% */] < 0.75992185f ? 
            27780.86f : 
             (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.726545E12f ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -68351.875f : 
                    -33056.324f) : 
                9458.13f)) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[3])) ? 
            -2350.2454f : 
            54954.996f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_2_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (data[4 /* Completion% */] < 0.75992185f ? 
            25002.76f : 
             (data[6 /* Start Date */] < 1.65658834E12f ? 
                -55121.492f : 
                 (data[4 /* Completion% */] < 0.85535157f ? 
                    12440.723f : 
                    -28185.01f))) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
            -2115.2205f : 
            49459.496f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_3_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (data[4 /* Completion% */] < 0.75992185f ? 
            22502.46f : 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.73428362E12f ? 
                 (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[1])) ? 
                    -58392.316f : 
                    -23810.969f) : 
                9705.775f)) : 
         (!Double.isNaN(data[5 /* Phase */]) && (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[5])) ? 
            3197.475f : 
            49358.93f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {20, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_4_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[5])) ? 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                -66583.5f : 
                 (data[6 /* Start Date */] < 1.64783627E12f ? 
                    -47952.285f : 
                     (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[1])) ? 
                        -10688.386f : 
                        49154.336f))) : 
            31101.18f) : 
        40546.605f);
    return pred;
  } // constant pool size = 42B, number of visited nodes = 5, static init size = 120B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {16, 0, 0, 0};
  // {01110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {14, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_5_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[6 /* Start Date */] < 1.67914583E12f ? 
                19614.252f : 
                -77076.61f) : 
             (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66597834E12f ? 
                -32659.547f : 
                51697.004f)) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[3])) ? 
            -4851.5728f : 
            39453.566f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_6_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.73428362E12f ? 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.6934585E12f ? 
                 (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.895f ? 
                     (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                        -14723.885f : 
                        44701.832f) : 
                    -30045.387f) : 
                -74330.65f) : 
            25481.982f) : 
        33569.027f);
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_7_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (data[4 /* Completion% */] < 0.75992185f ? 
            24635.645f : 
             (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
                 (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.8959036f ? 
                    -10690.779f : 
                    -67194.805f) : 
                2775.2317f)) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[3])) ? 
            -5881.661f : 
            33938.28f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {1, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_8_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
            -62006.723f : 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[3])) ? 
                -29547.387f : 
                 (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66305215E12f ? 
                    -1317.884f : 
                    67521.22f))) : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[3])) ? 
            -19723.244f : 
            58493.656f));
    return pred;
  } // constant pool size = 42B, number of visited nodes = 5, static init size = 120B
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {20, 0, 0, 0};
  // {01110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {14, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {6, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {1, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_9_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[7 /* End Date */] < 1.68688039E12f ? 
                17292.643f : 
                -64636.69f) : 
             (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66597834E12f ? 
                -25963.32f : 
                46868.38f)) : 
         (!Double.isNaN(data[5 /* Phase */]) && (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[5])) ? 
            -5114.7637f : 
            29818.273f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
  // {01101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {22, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_10 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_10_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_10_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.73428362E12f ? 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.6934585E12f ? 
                 (data[4 /* Completion% */] < 0.78015625f ? 
                    29711.31f : 
                     (data[7 /* End Date */] < 1.64653223E12f ? 
                        -31178.752f : 
                        4314.6675f)) : 
                -64305.074f) : 
            22930.793f) : 
        25143.064f);
    return pred;
  } // constant pool size = 27B, number of visited nodes = 5, static init size = 30B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_11 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_11_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_11_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[6 /* Start Date */] < 1.66071134E12f ? 
                -24618.87f : 
                -61265.215f) : 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.86492187f ? 
                57078.094f : 
                -15974.11f)) : 
         (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9548828f ? 
            -23098.342f : 
            57905.695f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_12 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_12_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_12_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        24749.734f : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -51034.676f : 
                9345.783f) : 
             (data[4 /* Completion% */] < 0.9549853f ? 
                -22274.266f : 
                52115.137f)));
    return pred;
  } // constant pool size = 28B, number of visited nodes = 4, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_13 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_13_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_13_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (data[7 /* End Date */] < 1.67107926E12f ? 
             (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[1])) ? 
                -34296.4f : 
                -16249.61f) : 
             (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[2])) ? 
                -30774.154f : 
                35013.965f)) : 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[0])) ? 
            -17385.559f : 
             (!Double.isNaN(data[5 /* Phase */]) && (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT4, 32, 0, data[5])) ? 
                398.9925f : 
                49570.12f)));
    return pred;
  } // constant pool size = 51B, number of visited nodes = 6, static init size = 150B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {00010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {8, 0, 0, 0};
  // {11100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {7, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {12, 0, 0, 0};
  // {10101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT4 = new byte[] {21, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_14 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_14_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_14_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        23264.828f : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.8949658f ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -53023.027f : 
                    53232.27f) : 
                -52477.76f) : 
             (data[4 /* Completion% */] < 0.9549853f ? 
                -19564.031f : 
                46008.223f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_15 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_15_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_15_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
             (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[5])) ? 
                 (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[3])) ? 
                    -40135.504f : 
                     (data[6 /* Start Date */] < 1.66363739E12f ? 
                        -33106.566f : 
                        4144.828f)) : 
                14511.584f) : 
            24465.527f) : 
        20237.887f);
    return pred;
  } // constant pool size = 42B, number of visited nodes = 5, static init size = 120B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {1, 0, 0, 0};
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {16, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_16 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_16_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_16_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.73428362E12f ? 
                 (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.68843713E12f ? 
                     (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[5])) ? 
                        -20516.53f : 
                        22863.87f) : 
                    -60812.23f) : 
                11457.494f) : 
            22018.977f) : 
        18214.086f);
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {1, 0, 0, 0};
  // {01001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {18, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_17 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_17_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_17_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        22320.764f : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.8949658f ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -46457.754f : 
                    47042.62f) : 
                -47646.56f) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                -17769.78f : 
                40740.445f)));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_18 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_18_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_18_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.70004788E12f ? 
             (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                 (data[4 /* Completion% */] < 0.83484375f ? 
                    -3602.7576f : 
                    -14834.866f) : 
                22832.615f) : 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.74338487E12f ? 
                -43198.53f : 
                8292.889f)) : 
        17403.309f);
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {9, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_19 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_19_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_19_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        20930.621f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.96496093f ? 
                 (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
                    -52788.633f : 
                    -15683.293f) : 
                19599.379f) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -20719.809f : 
                36114.934f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {20, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_20 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_20_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_20_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
                -31721.15f : 
                 (!Double.isNaN(data[5 /* Phase */]) && (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[5])) ? 
                    -24930.738f : 
                    30837.156f)) : 
            38840.79f) : 
         (data[6 /* Start Date */] < 1.72637972E12f ? 
            -49316.996f : 
            10755.565f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {3, 0, 0, 0};
  // {10101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {21, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_21 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_21_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_21_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        19307.93f : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.8949658f ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -38291.57f : 
                    40804.348f) : 
                -41782.37f) : 
             (data[4 /* Completion% */] < 0.9549853f ? 
                -17941.98f : 
                36929.793f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_22 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_22_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_22_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.73428362E12f ? 
                 (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.68843713E12f ? 
                     (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[5])) ? 
                        -17649.084f : 
                        18287.113f) : 
                    -49437.58f) : 
                8861.583f) : 
            16930.24f) : 
        17101.322f);
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {1, 0, 0, 0};
  // {01001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {18, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_23 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_23_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_23_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
            -20966.88f : 
             (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[2])) ? 
                 (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.90484375f ? 
                    3747.1052f : 
                    -32055.422f) : 
                24336.639f)) : 
        15391.187f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {5, 0, 0, 0};
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {3, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_24 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_24_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_24_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        17657.002f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.96496093f ? 
                 (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
                    -46558.492f : 
                    -12713.291f) : 
                15507.046f) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -15128.23f : 
                30217.092f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {20, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_25 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_25_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_25_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
                 (data[4 /* Completion% */] < 0.81953126f ? 
                    -9512.72f : 
                    -24262.777f) : 
                13778.116f) : 
            33626.72f) : 
         (data[6 /* Start Date */] < 1.72637972E12f ? 
            -41601.523f : 
            7976.5654f));
    return pred;
  } // constant pool size = 27B, number of visited nodes = 5, static init size = 30B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_26 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_26_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_26_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        16584.088f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.96496093f ? 
                 (data[4 /* Completion% */] < 0.82483274f ? 
                    -11784.509f : 
                    -41991.582f) : 
                14315.184f) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[0])) ? 
                -13008.85f : 
                26215.902f)));
    return pred;
  } // constant pool size = 27B, number of visited nodes = 5, static init size = 30B
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_27 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_27_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_27_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
                -23805.717f : 
                 (!Double.isNaN(data[5 /* Phase */]) && (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[5])) ? 
                    -19504.133f : 
                    26249.164f)) : 
            29677.393f) : 
         (data[6 /* Start Date */] < 1.72637972E12f ? 
            -37812.773f : 
            6189.747f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {3, 0, 0, 0};
  // {10101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {21, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_28 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_28_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_28_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
                 (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[1])) ? 
                    -21385.88f : 
                    -6864.7173f) : 
                13468.785f) : 
            26709.643f) : 
         (data[6 /* Start Date */] < 1.72637972E12f ? 
            -34031.496f : 
            5570.786f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {00010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {8, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_29 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_29_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_29_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        15910.818f : 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.8949658f ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -29187.518f : 
                    33925.99f) : 
                -36902.664f) : 
             (data[4 /* Completion% */] < 0.9549853f ? 
                -14873.327f : 
                31043.48f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {1, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {10, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_30 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_30_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_30_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.70004788E12f ? 
             (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                    -22882.697f : 
                    9268.45f) : 
                15465.677f) : 
             (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.74860783E12f ? 
                -27381.822f : 
                4070.5325f)) : 
        12978.807f);
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {9, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {6, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_31 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_31_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_31_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        14711.755f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.96496093f ? 
                 (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
                    -38690.504f : 
                    -8817.394f) : 
                10618.679f) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -8621.446f : 
                24177.035f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {20, 0, 0, 0};
  // {10010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {9, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_32 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_32_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_32_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.70004788E12f ? 
             (Double.isNaN(data[2 /* Department */]) || !GenModel.bitSetIsInRange(32, 0, data[2]) || (data[2] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                    -20697.863f : 
                    8946.307f) : 
                14760.311f) : 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.95953125f ? 
                -26373.453f : 
                4104.6377f)) : 
        11614.22f);
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {10010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {9, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {6, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_33 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_33_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_33_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        14172.361f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
                -34317.227f : 
                 (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9496875f ? 
                    -17085.186f : 
                    20762.627f)) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -8435.198f : 
                21058.488f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {3, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_34 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_34_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_34_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[4 /* Completion% */] < 0.8900781f ? 
                2454.254f : 
                -33949.93f) : 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
                -10746.522f : 
                25695.771f)) : 
        11312.659f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_35 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_35_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_35_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.70012102E12f ? 
         (Double.isNaN(data[7]) || data[7 /* End Date */] < 1.67124258E12f ? 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
                 (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                    -23058.91f : 
                    -1100.745f) : 
                12480.158f) : 
            20998.21f) : 
         (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
            -25851.404f : 
            7039.536f));
    return pred;
  } // constant pool size = 37B, number of visited nodes = 5, static init size = 90B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {01001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {18, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {6, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_36 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_36_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_36_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[4 /* Completion% */] < 0.8900781f ? 
                2083.7808f : 
                -30778.252f) : 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
                -9427.331f : 
                22776.377f)) : 
        10554.453f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_37 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_37_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_37_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9648633f ? 
         (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
            -24729.994f : 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
                -14536.636f : 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                    -4619.29f : 
                    32029.488f))) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[3])) ? 
            -20058.078f : 
            27151.664f));
    return pred;
  } // constant pool size = 42B, number of visited nodes = 5, static init size = 120B
  // {00111000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {28, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {10, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {1, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_38 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_38_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_38_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[6 /* Start Date */] < 1.66861183E12f ? 
                -30228.932f : 
                861.6f) : 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
                -8551.014f : 
                21156.482f)) : 
        9846.781f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_39 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_39_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_39_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
                 (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                    -19761.957f : 
                    -537.28f) : 
                11136.64f) : 
            17885.213f) : 
         (data[6 /* Start Date */] < 1.72637972E12f ? 
            -28009.852f : 
            5634.3833f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {10100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {5, 0, 0, 0};
  // {01001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {18, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_40 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_40_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_40_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9648633f ? 
         (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
            -22315.04f : 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[3])) ? 
                -13177.073f : 
                 (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[0])) ? 
                    -4902.77f : 
                    28607.95f))) : 
         (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT3, 32, 0, data[3])) ? 
            -18142.564f : 
            25388.553f));
    return pred;
  } // constant pool size = 42B, number of visited nodes = 5, static init size = 120B
  // {00111000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {28, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {01010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {10, 0, 0, 0};
  // {10000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT3 = new byte[] {1, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_41 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_41_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_41_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.80503905f ? 
         (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
            -12367.48f : 
            17252.969f) : 
         (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[1])) ? 
            -21945.477f : 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.959637f ? 
                -14064.569f : 
                21973.424f)));
    return pred;
  } // constant pool size = 28B, number of visited nodes = 4, static init size = 60B
  // {00011000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {24, 0, 0, 0};
  // {11100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {7, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_42 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_42_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_42_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[4 /* Completion% */] < 0.8900781f ? 
                2745.3174f : 
                -28027.078f) : 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
                -7489.907f : 
                19314.594f)) : 
        9184.847f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {12, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_43 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_43_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_43_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9648633f ? 
         (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
             (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[2])) ? 
                -22151.254f : 
                1679.7402f) : 
            11613.552f) : 
         (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[2])) ? 
            -13363.085f : 
            26739.662f));
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {4, 0, 0, 0};
  // {00101000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {20, 0, 0, 0};
  // {11001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {19, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_44 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_44_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_44_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.75992185f ? 
        10903.723f : 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.66861183E12f ? 
             (!Double.isNaN(data[3 /* Complexity */]) && (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
                -30123.15f : 
                 (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.9496875f ? 
                    -13490.821f : 
                    18378.922f)) : 
             (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                -8480.153f : 
                20905.023f)));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {3, 0, 0, 0};
  // {10010000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {9, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_45 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_45_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_45_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (data[6 /* Start Date */] < 1.63566191E12f ? 
            -6008.381f : 
             (!Double.isNaN(data[2 /* Department */]) && (GenModel.bitSetIsInRange(32, 0, data[2]) && (data[2] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[2])) ? 
                -10378.542f : 
                22007.342f)) : 
         (data[7 /* End Date */] < 1.73428362E12f ? 
            -25186.96f : 
            4579.0444f));
    return pred;
  } // constant pool size = 23B, number of visited nodes = 4, static init size = 30B
  // {10011000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {25, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_46 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_46_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_46_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[6 /* Start Date */] < 1.66861183E12f ? 
                -27418.771f : 
                -295.20715f) : 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.86492187f ? 
                 (data[4 /* Completion% */] < 0.7747983f ? 
                    8523.76f : 
                    -15001.627f) : 
                22569.607f)) : 
        8881.479f);
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_47 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_47_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_47_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.69216718E12f ? 
         (Double.isNaN(data[6]) || data[6 /* Start Date */] < 1.6632502E12f ? 
             (Double.isNaN(data[3 /* Complexity */]) || !GenModel.bitSetIsInRange(32, 0, data[3]) || (data[3] >= 3) || (GenModel.bitSetIsInRange(32, 0, data[3]) && (data[3] < 3) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[3])) ? 
                 (Double.isNaN(data[0 /* Project Type */]) || !GenModel.bitSetIsInRange(32, 0, data[0]) || (data[0] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
                    -24097.082f : 
                    15117.262f) : 
                14593.135f) : 
            15639.66f) : 
         (data[7 /* End Date */] < 1.73428362E12f ? 
            -22933.168f : 
            3710.7861f));
    return pred;
  } // constant pool size = 32B, number of visited nodes = 5, static init size = 60B
  // {01000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {2, 0, 0, 0};
  // {11000000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {3, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_48 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_48_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_48_class_0 {
  static final double score0(double[] data) {
    double pred =      (data[4 /* Completion% */] < 0.80503905f ? 
         (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[1])) ? 
            -7298.998f : 
            19127.967f) : 
         (!Double.isNaN(data[1 /* Region */]) && (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[1])) ? 
            -19814.416f : 
             (Double.isNaN(data[4]) || data[4 /* Completion% */] < 0.959637f ? 
                -12045.506f : 
                19300.068f)));
    return pred;
  } // constant pool size = 28B, number of visited nodes = 4, static init size = 60B
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {12, 0, 0, 0};
  // {11100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {7, 0, 0, 0};
}


class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Forest_49 {
  public static void score0(double[] fdata, double[] preds) {
    preds[0] += gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_49_class_0.score0(fdata);
  }
}
class gbm_a1d31c0a_288b_44e5_933a_a802108402d6_Tree_49_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[5 /* Phase */]) || !GenModel.bitSetIsInRange(32, 0, data[5]) || (data[5] >= 5) || (GenModel.bitSetIsInRange(32, 0, data[5]) && (data[5] < 5) && !GenModel.bitSetContains(GRPSPLIT0, 32, 0, data[5])) ? 
         (!Double.isNaN(data[0 /* Project Type */]) && (GenModel.bitSetIsInRange(32, 0, data[0]) && (data[0] < 4) && !GenModel.bitSetContains(GRPSPLIT1, 32, 0, data[0])) ? 
             (data[4 /* Completion% */] < 0.8900781f ? 
                1680.4365f : 
                -24260.383f) : 
             (Double.isNaN(data[1 /* Region */]) || !GenModel.bitSetIsInRange(32, 0, data[1]) || (data[1] >= 4) || (GenModel.bitSetIsInRange(32, 0, data[1]) && (data[1] < 4) && !GenModel.bitSetContains(GRPSPLIT2, 32, 0, data[1])) ? 
                -6149.1455f : 
                16572.678f)) : 
        8307.014f);
    return pred;
  } // constant pool size = 33B, number of visited nodes = 4, static init size = 90B
  // {00001000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT0 = new byte[] {16, 0, 0, 0};
  // {01100000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT1 = new byte[] {6, 0, 0, 0};
  // {00110000 00000000 00000000 00000000}
  public static final byte[] GRPSPLIT2 = new byte[] {12, 0, 0, 0};
}


